name: SBO Automation

on:
  schedule:
    - cron: '30 12 * * *'  # 6 PM IST (12:30 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run Selenium Script
        env:
          DISPLAY: ":99"
        run: |
          python3 main.py
